routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\PhotosController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('language')->group(function() {
    Route::get('/', [PhotosController::class, 'index'])->name('home');
    Route::resource('photos', PhotosController::class)->except(['edit', 'update']);
    Route::resource('users', UsersController::class)->only(['show', 'edit', 'update']);
    Route::resource('photos.comments', CommentsController::class)->only(['store',])
        ->middleware('auth');


    Auth::routes();

});
Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])->name('language.switcher')
    ->where('locale', 'en|ru');

app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Orchid\Screen\AsSource;

class Photo extends Model
{
    use HasFactory;
    use AsSource;

    /**
     * @var string[]
     */
    protected $fillable = ['denomination', 'photo', 'user_id'];


    /**
     * @return BelongsTo
     */
    public function user():BelongsTo
    {
        return $this->belongsTo(User::class);
    }


    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->latest();
    }
}

app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Form\PhotoActionsForm;
use App\Http\Requests\PhotoRequest;
use App\Models\Photo;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PhotosController extends Controller
{

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $photos = Photo::latest()->paginate(8);
        return view('clients.photos.index', compact('photos'));
    }


    /**
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Photo::class);
        return view('clients.photos.create');
    }


    /**
     * @param PhotoRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(PhotoRequest $request):RedirectResponse
    {
        $this->authorize('create', Photo::class);
        $photo = PhotoActionsForm::execute($request);
        $photo->save();
        return redirect()->route('users.show', $photo->user->id);

    }


    /**
     * @param Photo $photo
     * @return Application|Factory|View
     */
    public function show(Photo $photo)
    {
        $comments = $photo->comments()->orderByDesc('updated_at')->paginate(5);
        if($photo->comments->count() != 0) {
            $grade = $photo->comments()->avg('grade');
        } else {
            $grade = 0;
        }
        return view('clients.photos.show', compact('photo', 'grade', 'comments'));
    }


    /**
     * @param Photo $photo
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Photo $photo):RedirectResponse
    {
        $this->authorize('delete', $photo);
        $photo->delete();
        return redirect()->route('users.show', $photo->user_id);

    }
}

resources/views/clients/photos/create.blade.php
@extends('layouts.app')
@section('content')
    <div>
        <h3>@lang('messages.create_new_photo')</h3>
    </div>
    <form enctype="multipart/form-data" method="post" action="{{route('photos.store')}}">
        @csrf
        <div class="form-group mt-3">
            <label for="denomination">@lang('messages.denomination')</label>
            <input type="text"
                   class="form-control border-success  @error('denomination') is-invalid border-danger @enderror"
                   id="denomination" name="denomination">
        </div>
        @error('denomination')
        <p class="text-danger">{{ $message }}</p>
        @enderror
        <div class="form-group mt-3">
            <div class="custom-file">
                <label for="customFile">@lang('messages.choose_file')</label>
                <input type="file" class="custom-file-input @error('photo') is-invalid border-danger @enderror"
                       id="customFile" name="photo">
                <label class="custom-file-label" for="customFile">@lang('messages.choose_file')</label>
            </div>
        </div>
        @error('photo')
        <p class="text-danger">{{ $message }}</p>
        @enderror
        <button type="submit" class="btn btn-outline-primary">@lang('messages.save')</button>
    </form>
@endsection

resources/views/clients/photos/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="row gallery-list">
        @foreach($photos as $photo)
            <div class="col-md-3 gallery-list--item" style="padding: 35px 0 0 0;">
                <div class="card" style="width: 18rem; height: 100%">
                    <div class="img-wrapper">
                        <a href="{{route('photos.show', ['photo' => $photo])}}">
                            <img src="{{asset($photo->photo)}}" class="card-img"
                                 alt="{{asset($photo->photo)}}" height="100%">
                        </a>
                    </div>

                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title"><b>{{$photo->denomination}}</b></h5>
                    </div>

                    <div class="card-footer">
                        @lang('messages.author'): <a
                            href="{{route('users.show', ['user' => $photo->user])}}">{{$photo->user->name}}</a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="row justify-content-md-center p-5">
        <div class="col-md-auto">
            {{ $photos->links('pagination::bootstrap-4') }}
        </div>
    </div>
@endsection

resources/views/clients/photos/show.blade.php
@extends('layouts.app')
@section('content')

    <div>
        <h3><b>{{$photo->denomination}}</b></h3>
        <div class="card" style="width: 18rem;">
            <img src="{{asset($photo->photo)}}" class="card-img-one"
                 alt="{{asset($photo->photo)}}">
        </div>
    </div>

    <div>
        <p>@lang('messages.average_grade'): {{round($grade, 2)}}</p>
        @if($comments->count() > 0)
            <div class="list-group">
                @foreach($photo->comments as $comment)
                    <div class="list-group-item list-group-item-action shadow-lg">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="w-75">
                                <h5 class="mb-1">
                                    <a href="" class="text-decoration-none">{{ $comment->user->name }}</a>
                                </h5>
                                <p class="mb-1"><em>{{ $comment->content }}</em></p>
                                <span
                                    class="g-color-gray-dark-v4 g-font-size-12"><em>@lang('messages.adding'):{{$comment->created_at->diffForHumans()}}</em></span>
                            </div>
                        </div>
                    </div>
                @endforeach
                <div class="row justify-content-md-center mt-5">
                    <div class="col-md-auto">
                        {{ $comments->withQueryString()->links('pagination::bootstrap-4') }}
                    </div>
                </div>
                @endif
                @if(Auth::user() != $photo->user)
                    <h3 class="mt-5 mb-3"> @lang('messages.add_new_comment')</h3>
                    <form action="{{ route('photos.comments.store', $photo) }}" method="POST">
                        @csrf
                        <div class="input-group">
                            <label for="grade" style="margin-right: 5px;">@lang('messages.grade')</label>
                            <select class="form-control border-info  @error('grade') is-invalid border-danger @enderror"
                                    name="grade">
                                <option value="0" selected></option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                            @error('grade')
                            <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>
                        <div class="row">
                            <div class="input-group">
                        <textarea class="form-control border-info @error('content') is-invalid border-danger @enderror"
                                  name="content" aria-label="With textarea"
                                  cols="30" rows="5"></textarea>
                            </div>
                            @error('content')
                            <div class="text-danger">{{$message}}</div>
                            @enderror
                        </div>
                        <div class="row mt-2 mb-5">
                            <div class="col-12">
                                <button type="submit"
                                        class="btn btn-outline-info"> @lang('messages.add_new_comment')</button>
                            </div>
                        </div>
                    </form>
                @endif
            </div>
@endsection