routes/web.php
<?php

use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LanguageSwitcherController;
use App\Http\Controllers\PhotosController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('language')->group(function() {
    Route::get('/', [PhotosController::class, 'index'])->name('home');
    Route::resource('photos', PhotosController::class)->except(['edit', 'update']);
    Route::resource('users', UsersController::class)->only(['show', 'edit', 'update']);
    Route::resource('photos.comments', CommentsController::class)->only(['store',])
        ->middleware('auth');


    Auth::routes();

});
Route::get('language/{locale}', [LanguageSwitcherController::class, 'switcher'])->name('language.switcher')
    ->where('locale', 'en|ru');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Orchid\Platform\Models\User as Authenticatable;
use Orchid\Screen\AsSource;

class User extends Authenticatable
{
    use HasFactory;
    use AsSource;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'permissions',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'permissions',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'permissions'          => 'array',
        'email_verified_at'    => 'datetime',
    ];

    /**
     * The attributes for which you can use filters in url.
     *
     * @var array
     */
    protected $allowedFilters = [
        'id',
        'name',
        'email',
        'permissions',
    ];

    /**
     * The attributes for which can use sort in url.
     *
     * @var array
     */
    protected $allowedSorts = [
        'id',
        'name',
        'email',
        'updated_at',
        'created_at',
    ];


    /**
     * @return HasMany
     */
    public function photos():HasMany
    {
        return $this->hasMany(Photo::class);
    }


    /**
     * @return HasMany
     */
    public function comments():HasMany
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Form\UserActionsForm;
use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class UsersController extends Controller
{


    /**
     * @param User $user
     * @return Application|Factory|View
     */
    public function show(User $user)
    {
        return view('clients.users.show', compact('user'));
    }


    /**
     * @param User $user
     * @return Application|Factory|View
     * @throws AuthorizationException
     */
    public function edit(User $user)
    {
        $this->authorize('edit', $user);
        return view('clients.users.edit', compact('user'));
    }


    /**
     * @param UserRequest $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(UserRequest $request, User $user):RedirectResponse
    {
        $user = UserActionsForm::perform($request, $user);
        return redirect()->route( 'users.show', ['user' => $user]);

    }

}

resources/views/clients/users/edit.blade.php
@extends('layouts.app')
@section('content')
    <div>
        <h3>@lang('messages.edit')</h3>
    </div>
    <form enctype="multipart/form-data" method="post" action="{{route('users.update', ['user' => $user])}}">
        @method('put')
        @csrf
        <div class="form-group mb-3">
            <label for="name">@lang('messages.name')</label>
            <input type="text" class="form-control border-success  @error('name') is-invalid border-danger @enderror"
                   id="name" name="name" value="{{$user->name}}">
        </div>
        @error('name')
        <p class="text-danger">{{ $message }}</p>
        @enderror
        <button type="submit" class="btn btn-outline-primary">@lang('messages.save')</button>
    </form>
@endsection

resources/views/clients/users/show.blade.php
@extends('layouts.app')
@section('content')
    <h2><b>@lang('messages.prof')</b> {{$user->name}}
        @if($user->can('edit', App\Models\User::class))
            <a href="{{route('users.edit', ['user'=> $user])}}" class="btn btn-primary btn-sm active" role="button"
               aria-pressed="true">@lang('messages.edit')</a>
        @endcan
        @if($user->can('create', App\Models\Photo::class))
            <a href="{{route('photos.create')}}" class="btn btn-primary btn-sm active" role="button"
               aria-pressed="true">@lang('messages.create_new_photo')</a>
        @endif
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">@lang('messages.photo')</th>
                <th scope="col">@lang('messages.denomination')</th>
                <th scope="col">@lang('messages.action')</th>
            </tr>
            </thead>
            <tbody>

            @foreach($user->photos as $photo)
                <tr>
                    <td>
                        <a href="{{route('photos.show', ['photo' => $photo])}}">
                            <img src="{{asset($photo->photo)}}" class="card-img-top"
                                 alt="{{asset($photo->photo)}}" width="50" height="100%">
                        </a>
                    </td>
                    <td>{{$photo->denomination}}</td>
                    <td>
                        @can('delete', $photo)
                            <form style="float: left; margin-right: 12px;"
                                  action="{{route('photos.destroy', ['photo' => $photo])}}" method="post">
                                @method('delete')
                                @csrf
                                <button class="btn btn-danger btn-sm active ">@lang('messages.remove')</button>
                            </form>
                        @endcan
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
@endsection